version: '2'

services:

  speedtest:
    restart: always
    container_name: speedtest
    build: ./docker/speedtest
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_HOST=${SPEEDTEST_HOST}"
